name: Terraform Plan

on:
  workflow_dispatch: 
    inputs:
        terraform-plan:
            description: 'Terraform plan?'
            required: true
            type: string


env:
  AWS_REGION: eu-west-2  

jobs:
  plan:
    runs-on: ubuntu-24.04
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run checkov scan
        uses: bridgecrewio/checkov-action@v12

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
          
      - name: terraform plan
        uses: dflook/terraform-plan@v2
        with:
          path: Terraform