name: Push to Amazon ECR

on:
  workflow_dispatch: 
    inputs:
        docker-push:
            description: 'Do you want to push? Type "yes" to proceed'
            type: string

    

env:
  AWS_REGION: eu-west-2                           

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: true

    - name: Build and tag image 
      id: build-image
      run: |
        cd app
        aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 174350032095.dkr.ecr.eu-west-2.amazonaws.com
        docker build -t siada2/ecs .
        docker tag siada2/ecs:latest 174350032095.dkr.ecr.eu-west-2.amazonaws.com/siada2/ecs:latest
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 174350032095.dkr.ecr.eu-west-2.amazonaws.com/siada2/ecs:latest

    - name: Push to Amazon ECR
      run: |
        docker push 174350032095.dkr.ecr.eu-west-2.amazonaws.com/siada2/ecs:latest
      
        
    
    
  

        
